### PR TITLE
Pr/31

### PR DESCRIPTION
**Pull request by japneetkaurbhatia**

### CODE REVIEW

**Comment by japneetkaurbhatia** [comment]
@akshay399 Your branch is still creating conflicts. On merge dark mode isn't working

**Comment by akshay399** [comment]
> @akshay399 Your branch is still creating conflicts. On merge dark mode isn't working

I'll look into it

**Comment by akshay399** [comment]
I am getting bit confused while making PR, can i create a completely new issue and then make a PR?

**Comment by japneetkaurbhatia** [comment]
Yes just create a new PR

**Pull request closed without merging**
